version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: generalshop
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
volumes:
  data-mysql:
    name: data-mysql